title: TradeFlow
description: Your personal trading journal with AI-powered insights
baseurl: /TradeFlow
url: https://archreactor04.github.io

remote_theme: just-the-docs/just-the-docs@v0.10.0

color_scheme: dark

search_enabled: true
search.heading_level: 3

heading_anchor: true

nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2026 TradeFlow. Distributed under the MIT License."

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/archReactor04/TradeFlow"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "edit"

callouts:
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  info:
    title: Info
    color: blue

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
