title: TradeFlow
description: Your personal trading journal with AI-powered insights
theme: just-the-docs

url: https://archreactor04.github.io/TradeFlow

color_scheme: tradeflow

aux_links:
  GitHub: https://github.com/archReactor04/TradeFlow

mermaid:
  version: "10.9.3"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav_fold: true
