title: TradeFlow
description: Your personal trading journal with AI-powered insights
theme: just-the-docs

url: https://archreactor04.github.io/TradeFlow

color_scheme: dark

aux_links:
  GitHub Repository: https://github.com/archReactor04/TradeFlow
